development:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgres'
  pool: '5'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'masterkey'

test:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgres'
  pool: '5'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'masterkey'

production:
  adapter: 'postgresql'
  encoding: 'unicode'
  database: 'postgres'
  pool: '5'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'masterkey'